---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: relintdockerhubpushbot/cf-deployment-concourse-tasks
    tag: v2.5.0

inputs:
  - name: dns-release
  - name: envs

params:
  ENV_NAME: default

run:
  path: dns-release/ci/tasks/clean-up.sh
