---
jobs:
- name: test-unit
  public: true
  plan:
    - get: dns-release
      trigger: true
    - task: test-unit
      file: dns-release/ci/tasks/test-unit.yml

- name: test-unit-windows
  public: true
  plan:
    - get: dns-release
      trigger: true
    - task: test-unit-windows
      file: dns-release/ci/tasks/test-unit-windows.yml

- name: test-performance
  public: true
  plan:
    - get: dns-release
      trigger: true
      passed: [test-unit]
    - get: bosh-candidate-stemcell
    - get: bosh-candidate-release
    - task: test-performance
      privileged: true
      file: dns-release/ci/tasks/test-performance.yml
      params:
        ZONES_JSON_HASH: {{zones_json_hash}}

- name: test-acceptance
  public: true
  plan:
    - get: dns-release
      trigger: true
      passed: [test-unit]
    - get: bosh-candidate-stemcell
    - get: bosh-candidate-release
    - task: test-acceptance
      privileged: true
      file: dns-release/ci/tasks/test-acceptance.yml

- name: test-acceptance-windows
  public: true
  serial: true
  serial_groups:
  - windows-acceptance-env
  plan:
    - get: dns-release
      trigger: true
      passed: [test-unit-windows]
    - get: envs
    - get: bosh-deployment
    - get: gcp-linux-stemcell
    - get: bosh-candidate-stemcell-windows
    - get: bosh-candidate-release
    - do:
      - task: windows
        file: dns-release/ci/tasks/test-acceptance-windows.yml
      - task: windows-nameserver-disabled
        file: dns-release/ci/tasks/test-acceptance-windows-nameserver-disabled.yml
      - task: windows-shared
        file: dns-release/ci/tasks/test-acceptance-windows-shared.yml
      ensure:
        task: clean-up
        file: dns-release/ci/tasks/clean-up.yml

- name: bbl-up
  serial: true
  serial_groups:
  - windows-acceptance-env
  plan:
    - get: dns-release
    - get: bosh-deployment
    - get: bosh-candidate-release
    - get: envs
    - task: bbl-up
      file: dns-release/ci/tasks/bbl-up.yml
      params:
        BBL_GCP_SERVICE_ACCOUNT_KEY: {{bbl_gcp_service_account_key_id}}
      ensure:
        put: envs
        params:
          repository: envs

- name: bbl-destroy
  serial: true
  serial_groups:
  - windows-acceptance-env
  plan:
    - get: dns-release
    - get: envs
    - task: bbl-destroy
      file: dns-release/ci/tasks/bbl-destroy.yml
      params:
        BBL_GCP_SERVICE_ACCOUNT_KEY: {{bbl_gcp_service_account_key_id}}
      ensure:
        put: envs
        params:
          repository: envs

resources:
- name: dns-release
  type: git
  source:
    uri: https://github.com/cloudfoundry/dns-release
    branch: master

- name: bosh-deployment
  type: git
  source:
    uri: https://github.com/cloudfoundry/bosh-deployment
    branch: master

- name: bosh-candidate-stemcell
  type: s3
  source:
    bucket: bosh-core-stemcells-candidate
    regexp: warden/bosh-stemcell-(.+)-warden-boshlite-ubuntu-trusty-go_agent.tgz

- name: bosh-candidate-stemcell-windows
  type: s3
  source:
    bucket: bosh-windows-stemcells-release-candidates
    regexp: light-bosh-stemcell-(.+)-google-kvm-windows2012R2-go_agent.tgz

- name: bosh-candidate-release
  type: s3
  source:
    bucket: bosh-candidate-release-tarballs
    versioned_file: bosh-dev-release.tgz

- name: gcp-linux-stemcell
  type: bosh-io-stemcell
  source:
    name: bosh-google-kvm-ubuntu-trusty-go_agent

- name: envs
  type: git
  source:
    branch: master
    uri: git@github.com:cloudfoundry/dns-release-ci-envs.git
    private_key: {{envs_private_key}}
